---

R1:
    hostname: "10.10.10.31"
    groups:
        - all_devices

    data:
        int_count: 4
        gig2_ip: "10.10.13.1"
        gig2_netmask: "255.255.255.0"
        gig3_ip: "10.10.14.1"
        gig3_netmask: "255.255.255.0"
        gig4_ip: "10.10.17.1"
        gig4_netmask: "255.255.255.0"
        gig5_ip: "10.10.15.1"
        gig5_netmask: "255.255.255.0"
        loop0_ip: "10.0.0.1"
        loop0_netmask: "255.255.255.255"
        
R2:
    hostname: "10.10.10.32"
    groups:
        - all_devices

    data:
        int_count: 4
        gig2_ip: "10.10.24.2"
        gig2_netmask: "255.255.255.0"
        gig3_ip: "10.10.23.2"
        gig3_netmask: "255.255.255.0"
        gig4_ip: "10.10.27.2"
        gig4_netmask: "255.255.255.0"
        gig5_ip: "10.10.26.2"
        gig5_netmask: "255.255.255.0"
        loop0_ip: "10.0.0.2"
        loop0_netmask: "255.255.255.255"

R3:
    hostname: "10.10.10.33"
    groups:
        - all_devices
    data:
        int_count: 3
        gig2_ip: "10.10.13.3"
        gig2_netmask: "255.255.255.0"
        gig3_ip: "10.10.23.3"
        gig3_netmask: "255.255.255.0"
        gig4_ip: "10.10.35.3"
        gig4_netmask: "255.255.255.0"
        gig5_ip: "no ip address"
        gig5_netmask: ""
        loop0_ip: "10.0.0.3"
        loop0_netmask: "255.255.255.255"

R4:
    hostname: "10.10.10.34"
    groups:
        - all_devices
    data:
        int_count: 3
        gig2_ip: "10.10.24.4"
        gig2_netmask: "255.255.255.0"
        gig3_ip: "10.10.14.4"
        gig3_netmask: "255.255.255.0"
        gig4_ip: "10.10.46.4"
        gig4_netmask: "255.255.255.0"
        gig5_ip: "no ip address"
        gig5_netmask: ""
        loop0_ip: "10.0.0.4"
        loop0_netmask: "255.255.255.255"

R5:
    hostname: "10.10.10.35"
    groups:
        - all_devices
    data:
        int_count: 2
        gig2_ip: "10.10.15.5"
        gig2_netmask: "255.255.255.0"
        gig3_ip: "10.10.35.5"
        gig3_netmask: "255.255.255.0"
        gig4_ip: "no ip address"
        gig4_netmask: ""
        gig5_ip: "no ip address"
        gig5_netmask: ""
        loop0_ip: "10.0.0.5"
        loop0_netmask: "255.255.255.255"

R6:
    hostname: "10.10.10.36"
    groups:
        - all_devices
    data:
        int_count: 2
        gig2_ip: "10.10.26.6"
        gig2_netmask: "255.255.255.0"
        gig3_ip: "10.10.46.6"
        gig3_netmask: "255.255.255.0"
        gig4_ip: "no ip address"
        gig4_netmask: ""
        gig5_ip: "no ip address"
        gig5_netmask: ""
        loop0_ip: "10.0.0.6"
        loop0_netmask: "255.255.255.255"

R7:
    hostname: "10.10.10.37"
    groups:
        - all_devices
    data:
        int_count: 2
        gig2_ip: "10.10.17.7"
        gig2_netmask: "255.255.255.0"
        gig3_ip: "10.10.27.7"
        gig3_netmask: "255.255.255.0"
        gig4_ip: "no ip address"
        gig4_netmask: ""
        gig5_ip: "no ip address"
        gig5_netmask: ""
        loop0_ip: "10.0.0.7"
        loop0_netmask: "255.255.255.255"