---

R1:
    hostname: "10.10.10.31"
    groups:
        - all_devices

    data:
        gig2_ip: "ip address 10.10.13.1 255.255.255.0"
        gig3_ip: "ip address 10.10.14.1 255.255.255.0"
        gig4_ip: "ip address 10.10.17.1 255.255.255.0"
        gig5_ip: "ip address 10.10.15.1 255.255.255.0"
        loop0_ip: "ip address 10.0.0.1 255.255.255.255"
        
R2:
    hostname: "10.10.10.32"
    groups:
        - all_devices

    data:
        gig2_ip: "ip address 10.10.24.2 255.255.255.0"
        gig3_ip: "ip address 10.10.23.2 255.255.255.0"
        gig4_ip: "ip address 10.10.27.2 255.255.255.0"
        gig5_ip: "ip address 10.10.26.2 255.255.255.0"
        loop0_ip: "ip address 10.0.0.2 255.255.255.255"

R3:
    hostname: "10.10.10.33"
    groups:
        - all_devices
    data:
        gig2_ip: "ip address 10.10.13.3 255.255.255.0"
        gig3_ip: "ip address 10.10.23.3 255.255.255.0"
        gig4_ip: "ip address 10.10.35.3 255.255.255.0"
        gig5_ip: "no ip address"
        loop0_ip: "ip address 10.0.0.3 255.255.255.255"

R4:
    hostname: "10.10.10.34"
    groups:
        - all_devices
    data:
        gig2_ip: "ip address 10.10.24.4 255.255.255.0"
        gig3_ip: "ip address 10.10.14.4 255.255.255.0"
        gig4_ip: "ip address 10.10.46.4 255.255.255.0"
        gig5_ip: "no ip address"
        loop0_ip: "ip address 10.0.0.4 255.255.255.255"

R5:
    hostname: "10.10.10.35"
    groups:
        - all_devices
    data:
        gig2_ip: "ip address 10.10.15.5 255.255.255.0"
        gig3_ip: "ip address 10.10.35.5 255.255.255.0"
        gig4_ip: "no ip address"
        gig5_ip: "no ip address"
        loop0_ip: "ip address 10.0.0.5 255.255.255.255"

R6:
    hostname: "10.10.10.36"
    groups:
        - all_devices
    data:
        gig2_ip: "ip address 10.10.26.6 255.255.255.0"
        gig3_ip: "ip address 10.10.46.6 255.255.255.0"
        gig4_ip: "no ip address"
        gig5_ip: "no ip address"
        loop0_ip: "ip address 10.0.0.6 255.255.255.255"

R7:
    hostname: "10.10.10.37"
    groups:
        - all_devices
    data:
        gig2_ip: "ip address 10.10.17.7 255.255.255.0"
        gig3_ip: "ip address 10.10.27.7 255.255.255.0"
        gig4_ip: "no ip address"
        gig5_ip: "no ip address"
        loop0_ip: "ip address 10.0.0.7 255.255.255.255"